# Generated by Django 4.0.2 on 2022-04-12 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
    ]
