# Generated by Django 4.0.4 on 2022-04-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music2', '0006_alter_artist_id_alter_rating_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='song',
            field=models.CharField(max_length=100),
        ),
    ]
