# Generated by Django 4.0.4 on 2022-04-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music2', '0011_alter_rating_unique_together_alter_rating_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
